from __future__ import annotations


PLOT_STATUS_AWAITING_SKELETON = "awaiting_skeleton"
PLOT_STATUS_PLANNING_BLOCKED = "planning_blocked"
PLOT_STATUS_AWAITING_SEAMS = "awaiting_seams"
PLOT_STATUS_READY = "ready"
PLOT_STATUS_GENERATING = "generating"
PLOT_STATUS_REPAIR_REQUIRED = "repair_required"
PLOT_STATUS_COMPLETED = "completed"
PLOT_STATUS_FAILED = "failed"
PLOT_STATUS_CANCELLED = "cancelled"

PLOT_ACTIVE_STATUSES = frozenset(
    {
        PLOT_STATUS_AWAITING_SKELETON,
        PLOT_STATUS_PLANNING_BLOCKED,
        PLOT_STATUS_AWAITING_SEAMS,
        PLOT_STATUS_READY,
        PLOT_STATUS_GENERATING,
        PLOT_STATUS_REPAIR_REQUIRED,
    }
)
PLOT_TERMINAL_STATUSES = frozenset(
    {
        PLOT_STATUS_COMPLETED,
        PLOT_STATUS_FAILED,
        PLOT_STATUS_CANCELLED,
    }
)
PLOT_STATUSES = PLOT_ACTIVE_STATUSES | PLOT_TERMINAL_STATUSES
